<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Monitoring Production</title>
    <link rel="stylesheet" href="../assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="../assets/css/styles.css">
    <link rel="stylesheet" href="../assets/css/Pretty-Header.css">
</head>
<body>
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="../index.php">Pertamina EP Asset 5</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="TOSUMM/B02.php">TOS UMM</a></li>
      <li><a href="M1/B02.php">SP M-1</a></li>
      <li><a href="B1/B02.php">SP B-1</a></li>
      <li><a href="C2/B02.php">SP C-2</a></li>
      <li><a href="A1/B02.php">SP A-1</a></li>
      <li><a href="D/B02.php">SP D</a></li>
      <li><a href="../index.php"><< HOME</a></li>
    </ul>
  </div>
</nav>
</body>
</html>